language: java
jdk: openjdk8
services:
  - docker
before_install:
  - wget -P ../ https://raw.githubusercontent.com/markoambrozic/rso/master/pom.xml
install:
  - mvn -N io.takari:maven:wrapper
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t markoambrozic/emailing:1.0.3 .
  - docker push markoambrozic/emailing
before_deploy:
  - cd deploy
  - chmod +x ./deploy.sh
deploy:
  provider: script
  script: ./deploy.sh
  on:
    repo: markoambrozic/emailing
    branch: master
  skip_cleanup: true
cache:
  directories:
    - $HOME/.m2
branches:
  only:
    - master